---
- name: "[{{ name }}] Deploy service"
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ docker_registry }}/{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - published_port: 3306
            target_port: 3306
            protocol: tcp
            mode: ingress
        placement:
          constraints:
            - "node.hostname == home-cluster-1"
