---
- name: Deploy server
  hosts: main
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
    # - swarm_init

- name: Manager
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join

- name: Worker
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
